### ISSUE TITLE
Make `Type` dyn-safe

### ISSUE THREAD

**Issue by Brendonovich** [oscartbeaumont/specta#127]
Restrict all static methods of `Type` to `where Self: Sized` so that `Type` can be dyn-safe.

**Comment by oscartbeaumont** [comment]
Do you have an intended use case for this? `NamedType` will never be dyn-safe so idk that making `Type` dyn-safe will be that useful. It probably can't hurt though cause we don't support any unsized types right now.

**Comment by Brendonovich** [comment]
I wanted to try representing typesafe errors as `Box<dyn Serialize + Type>` but thiserror doesn't exactly like it. I don't think it'll work anyway so we might be able to just close this.

**Comment by Brendonovich** [comment]
unnecessary nvm
