### ISSUE TITLE
Export docs for each attribute

### ISSUE THREAD

**Issue by IgnisDa** [oscartbeaumont/specta#144]
Specta not export docs for each field of an enum.

I have added doc comments for the field but specta does not export them.
https://github.com/IgnisDa/ryot/blob/1dea787774047b40a20fea35143fef783b004c27/apps/backend/src/models.rs#L517-L572

This was raised [here](https://github.com/oscartbeaumont/specta/issues/95#issuecomment-1651175291) but I figured it warranted a separate issue.

**Comment by oscartbeaumont** [comment]
Yeah, this was 100% an oversight of the initial doc comment exporter. Will hopefully get this fixed for the next release as I am hoping to get deprecated support too and they are the same code paths.
