### ISSUE TITLE
Compilation breakage of 2.0.0-rc.4

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [oscartbeaumont/specta#152]
To reproduce, create an empty crate, add
```
[dependencies]
specta = { version = "2.0.0-rc.4", features = ["typescript"] }
```
and run `cargo check`.

```
error[E0432]: unresolved import `crate::js_doc`
 --> .../specta-2.0.0-rc.4/src/lang/ts/comments.rs:1:5
  |
1 | use crate::js_doc;
  |     ^^^^^^^^^^^^^ no `js_doc` in the root
```

---
(Thank you for the great library, by the way! Happily use it in several pet projects.)

**Comment by oscartbeaumont** [comment]
Thanks for reporting this should be fixed in [v2.0.0-rc.5](https://github.com/oscartbeaumont/specta/releases/tag/v2.0.0-rc.5). Lemme know if it doesn't go away!
