### ISSUE TITLE
Incorrect type generation for Result<Vec<Enum>>

### ISSUE THREAD

**Issue by franciscoBSalgueiro** [oscartbeaumont/specta#156]
I'm not sure if it's a problem with tauri-specta or specta, but it seems to only happen when using an async fn in tauri.

Here's a minimal example:

```rust
#[derive(Serialize, Type)]
pub enum MyEnum {
    A(String),
    B(u32),
}

#[tauri::command]
#[specta::specta]
async fn test() -> Result<Vec<MyEnum>, ()> {
    Ok(vec![])
}
```

results in the following type definition:

```ts
async test() : Promise<__Result__<{ A: string } | { B: number }[], null>>
```

which isn't correct because only the second part of the union is an array.

Versions:

specta = 2.0.0-rc.5
tauri-specta = 2.0.0-rc.2

**Comment by oscartbeaumont** [comment]
You should be able to add the following in your `Cargo.toml` (or workspace root `Cargo.toml`) to fix the problem until the next Specta release:

```rust
[patch.crates-io]
specta = { git = "https://github.com/oscartbeaumont/specta", rev = "034a9c028639881878455f21c5d8667bbe53c42b" }
```
