### ISSUE TITLE
External Crate Types like `Vec2` Missing in `type_map`, Causes Panic

### ISSUE THREAD

**Issue by bennoinbeta** [oscartbeaumont/specta#163]
I've encountered an issue where external crate types (e.g., `Vec2` from `glam`) are not appearing in the type_map, despite the Rust compiler having no complaints. The absence of these types leads to a runtime panic.

For example, here's a snippet of relevant logs where the `Vec2` (from `glam`) Type isn't present in the `type_map`:
```
is_valid_ty: Reference(DataTypeReference { name: "Vec2", sid: SpectaID { type_name: "Vec2", hash: 11936166344375486694 }, generics: [] })

thread 'main' panicked at 'Reference type not found for 'SpectaID { type_name: "Vec2", hash: 11936166344375486694 }' in type map: [SpectaID { type_name: "Anchor", hash: 11130656607452671519 }, SpectaID { type_name: "AnchorCommand", hash: 13260037903619321928 }, SpectaID { type_name: "BlendMixin", hash: 1723160997900146064 }, SpectaID { type_name: "BlendMode", hash: 8045237701478367695 }, SpectaID { type_name: "ChildrenMixin", hash: 4564161160596600703 }, SpectaID { type_name: "CompositionMixin", hash: 18220908835960924506 }, SpectaID { type_name: "Frame", hash: 17495936038054179988 }, SpectaID { type_name: "FromJsEvent", hash: 14528508349893344538 }, SpectaID { type_name: "Group", hash: 15764305072385891346 }, SpectaID { type_name: "Infallible", hash: 3456712731521643166 }, SpectaID { type_name: "LayoutMixin", hash: 12342620546851051678 }, SpectaID { type_name: "Node", hash: 9636637039981211087 }, SpectaID { type_name: "NodeType", hash: 11512995350479546216 }, SpectaID { type_name: "ParentMixin", hash: 12977093173683817954 }, SpectaID { type_name: "PathMixin", hash: 9266507765207954675 }, SpectaID { type_name: "Rectangle", hash: 2924795972224220850 }, SpectaID { type_name: "RectangleCornerMixin", hash: 2416528462111344943 }, SpectaID { type_name: "RenderChange", hash: 2409048842531548835 }, SpectaID { type_name: "Selected", hash: 1600939123145587680 }, SpectaID { type_name: "ToJsEvent", hash: 5733880197138809511 }, SpectaID { type_name: "WorldIds", hash: 12519201065246680858 }]', 
```

Logs are generated from the following code segment (local):
```
.expect(
    format!(
        "Reference type not found for '{:?}' in type map: {:?}",
        ty.sid,
        type_map.keys().collect::<Vec<_>>()
    )
    .as_str(),
)
```

Stack trace starts at:
```
/Users/benno/Desktop/workspace/contribution/code/specta/src/serde.rs:79:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_display
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:150:5
   3: core::panicking::panic_str
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:134:5
   4: core::option::expect_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/option.rs:1952:5
   5: core::option::Option<T>::expect
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/option.rs:898:21
   6: specta::serde::is_valid_ty
             at /Users/benno/Desktop/workspace/contribution/code/specta/src/serde.rs:76:22
   7: specta::serde::is_valid_ty
             at /Users/benno/Desktop/workspace/contribution/code/specta/src/serde.rs:39:21
   8: specta::lang::ts::export_named_datatype
             at /Users/benno/Desktop/workspace/contribution/code/specta/src/lang/ts/mod.rs:92:5
   9: specta::export::ts::ts_with_cfg
             at /Users/benno/Desktop/workspace/contribution/code/specta/src/export/ts.rs:56:17
  10: specta::export::ts::ts
             at /Users/benno/Desktop/workspace/contribution/code/specta/src/export/ts.rs:9:5
  11: cli::generate_ts_types
             at ./src/bin.rs:46:11
  12: cli::main
             at ./src/bin.rs:39:13
  13: core::ops::function::FnOnce::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Suspected Cause

Your recent comment (in [Discord](https://discord.com/channels/949090953497567312/1166285954013724702) suggests that `export = false` may control the type's overall exportation, which could be a bug?

### Expected Behavior
`Vec2` and other external types should be properly recognized and added to the `type_map`.

### Steps to Reproduce
> Note: I'll try to create a bare bone reproduction repo tomorrow but for now here are the reproduction steps in the original repo:

1. Checkout: https://github.com/dyndotart/monorepo/blob/7-plan-research-rendering-engine-dtom/
2. `cd packages/dtom/rust`
3. Run `RUST_BACKTRACE=1 cargo run --features cli -- generate-ts-types --export-path ./test.ts`

### Additional Information
- `cargo 1.72.0 (103a7ff2e 2023-08-15)`
- `rustc 1.72.0 (5680fa18f 2023-08-23)`
- [Discord Thread](https://discord.com/channels/949090953497567312/1166285954013724702)

`Cargo.toml` (stripped)
```
[package]
name = "dyn-dtom"
version = "0.0.1"
authors = ["BennoDev <57860196+bennoinbeta@users.noreply.github.com>"]
edition = "2021"

[lib]
name = "dyn_dtom"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "cli"
path = "src/bin.rs"

[features]
cli = ["clap", "specta/export"]

[dependencies]
# ..
glam = { version = "0.24.2", features = ["serde"] }
# Latest version but rn local for testing
specta = { path = "/Users/benno/Desktop/workspace/contribution/code/specta", features = [
    "typescript",
    "serde",
    "glam",
    "bevy_ecs",
] }

# ..
```
[Original `Cargo.toml`](https://github.com/dyndotart/monorepo/blob/7-plan-research-rendering-engine-dtom/packages/dtom/rust/Cargo.toml)

---

Thank you for taking the time to look into this. I appreciate your work on the project and am looking forward to your guidance to resolve this issue. Thanks :)

**Comment by oscartbeaumont** [comment]
Digging into this from what I can see I have mixed up two concepts.

We store an `export` property and it's being used for two purposes:
 1. Given it's included in the TypeMap, should the type be included in the `.ts` file 
 2. Should the type be collected to the global type map on startup (as part of the `export` feature)
 
For the glam types we *don't* want them collected up into the global type map on startup as they may contain an BigInt type which is an error by default. We only want the error to be throw if the type is actually used. This corresponds with point 2. 

Point 1 is literally just a bug (and the one you hit). It causes a type to not be exported despite being referenced by another type, which Specta's treats as something that should never happen (hence the panic).

The first point should really be covered by the planned [export contexts](https://github.com/oscartbeaumont/specta/issues/39) feature so I am fine dropping the functionality of point 1 with no replacement for now given how it wasn't properly implemented so no one could have been using it.

It's funny I actually had a `TODO` in the code and issue #103 to go back and check the `TODO` which is actually related to the same problem this issue hit.

**Comment by bennoinbeta** [comment]
> Digging into this from what I can see I have mixed up two concepts.
> 
> We store an `export` property and it's being used for two purposes:
> 
> 1. Given it's included in the TypeMap, should the type be included in the `.ts` file
> 2. Should the type be collected to the global type map on startup (as part of the `export` feature)
> 
> For the glam types we _don't_ want them collected up into the global type map on startup as they may contain an BigInt type which is an error by default. We only want the error to be throw if the type is actually used. This corresponds with point 2.
> 
> Point 1 is literally just a bug (and the one you hit). It causes a type to not be exported despite being referenced by another type, which Specta's treats as something that should never happen (hence the panic).
> 
> The first point should really be covered by the planned [export contexts](https://github.com/oscartbeaumont/specta/issues/39) feature so I am fine dropping the functionality of point 1 with no replacement for now given how it wasn't properly implemented so no one could have been using it.
> 
> It's funny I actually had a `TODO` in the code and issue #103 to go back and check the `TODO` which is actually related to the same problem this issue hit.

so the problem will be (indirectly) solved when the "export contexts" feature got implemented?

**Comment by oscartbeaumont** [comment]
In https://github.com/oscartbeaumont/specta/commit/54077168eb5416290cc3db4fd43e686e0de1a35d I removed all code related to supporting point 1 which *should* solve the issue you had. Give it a shot and let me know if you still hit the panic!

Sorry if the explanation wasn't clear, I'm super tired and the explanation probably doesn't matter too much anyway, it's more useful for future me if I ever come back to this issue.
