### ISSUE TITLE
Conflict between `Record<string, never>` and Serde Tag in TypeScript Output

### ISSUE THREAD

**Issue by bennoinbeta** [oscartbeaumont/specta#174]
### Description
In Specta, an empty struct is represented as `Record<string, never>` in the TypeScript output, which conflicts with the [Serde `tag = type`](https://serde.rs/enum-representations.html#internally-tagged) pattern. 
![image](https://github.com/oscartbeaumont/specta/assets/57860196/3429cd45-16dc-4781-97da-2f722f80d85d)

### Suggested Change
It's suggested to modify the handling of empty structs in TypeScript output, particularly in cases where Serde's `tag` is involved. Instead of using `{}` in general (which is not a good practice as explained in [Total TypeScript - The Empty Object Type in TypeScript](https://www.totaltypescript.com/the-empty-object-type-in-typescript)), the solution might involve a conditional approach based on the presence of Serde's `tag`.

More context: https://discord.com/channels/949090953497567312/1176756946796298310/1176761059764351127

**Comment by bennoinbeta** [comment]
@oscartbeaumont 

Thanks for the quick action. Though for me the proposed fix didn't work :/

Logs
```
--- Named: NamedFields {
    fields: [],
    tag: None,
}
--- Named: NamedFields {
    fields: [],
    tag: None,
}
```

Code
```rs
#[derive(Debug, Deserialize, Type, Clone)]
#[serde(tag = "type")]
pub enum InteractionInputEvent {
    CursorEnteredComposition(CursorEnteredComposition),
    CursorExitedComposition(CursorExitedComposition),
    // ..
}
}

// ..

#[derive(Event, Debug, Deserialize, Type, Clone)]
pub struct CursorEnteredComposition {} // TODO: Change back to Unit struct when https://github.com/oscartbeaumont/specta/issues/174 fixed

#[derive(Event, Debug, Deserialize, Type, Clone)]
pub struct CursorExitedComposition {} // TODO: Change back to Unit struct when https://github.com/oscartbeaumont/specta/issues/174 fixed

// ..
```

Typescript output:
```ts
export type CursorEnteredComposition = Record<string, never>

export type CursorExitedComposition = Record<string, never>

export type InteractionInputEvent = ({ type: "CursorEnteredComposition" } & CursorEnteredComposition) | ({ type: "CursorExitedComposition" } & CursorExitedComposition)
```

**Comment by oscartbeaumont** [comment]
Ohhhh, now I get you.

Checking with what Serde do the expected behavior should be :

## `pub struct Inner {}`

Previously: `{ "tag": "tagValue" } & Record<string, never>`
Expected: `{ "tag":"tagValue" }`

## `pub struct Inner`

Previously: `{ "tag": "tagValue" } & null` which Typescript coalesces to `never`.
Expected: `{ "tag":"tagValue" }`

It looks like we already have a check related to this in place but it's not working correctly with references. Eg. it checks for the string `null` but in this case it would be `Inner` so the check fails.

## `pub struct Inner()`

Previously: `{ "tag": "tagValue" } & []`
Expected: Invalid Type Error

**Comment by oscartbeaumont** [comment]
Okay give https://github.com/oscartbeaumont/specta/commit/467e2b083c802086da2c2b9caeced1509d4a0000 a shot and lemme know if you still are having issues.

**Comment by bennoinbeta** [comment]
> Okay give [467e2b0](https://github.com/oscartbeaumont/specta/commit/467e2b083c802086da2c2b9caeced1509d4a0000) a shot and lemme know if you still are having issues.

Seems to work as expected :)

Thanks a lot for the quick fixes 👍 🙏 


```ts
export type InteractionInputEvent = ({ type: "CursorDownOnEntity" } & CursorDownOnEntity) | ({ type: "CursorMovedOnComposition" } & CursorMovedOnComposition) | ({ type: "CursorEnteredComposition" }) | ({ type: "CursorExitedComposition" })
```
