### ISSUE TITLE
Ability to define classes

### ISSUE THREAD

**Issue by indietyp** [oscartbeaumont/specta#195]
From what I understood it's currently not possible to generate classes into Typescript. This is especially useful in use-cases like `wasm-bindgen`.

**Comment by oscartbeaumont** [comment]
I am going to close this due to the logic in the explanation [here](https://github.com/oscartbeaumont/specta/issues/197#issuecomment-1868431407). I love the idea, I just think it's better done on top of Specta not within Specta.
