### ISSUE TITLE
Document how to `#[derive(specta::Type)]` a struct with fields of external types

### ISSUE THREAD

**Issue by ctison** [oscartbeaumont/specta#210]
Hello, I have the following type:
```rs
#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
pub struct Person {
  id: surrealdb::sql::Thing,
}
```
But the following error occurs: ```the trait bound `surrealdb::sql::Thing: specta::Type` is not satisfied```.
Is there a way to make it work?

Because as a way arround, I used a generic parameter but it takes two type definitions for one:
```rs
#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
pub struct _Person<I> {
  id: I,
}
pub type Person = _Person<surrealdb::sql::Thing>;
```

Thanks

**Comment by oscartbeaumont** [comment]
You should be able to do use a type override (`type =`).

```rust
#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
pub struct ThingDef {
    pub tb: String,
    pub id: Id,

#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
pub struct Person {
  #[specta(type = ThingDef)]
  id: surrealdb::sql::Thing,
}
```

Alternatively, you could just convert `surrealdb::sql::Thing` into `ThingDef` using `From`. That would be required if you want something like `HashMap<String, Thing>` as `type =` can't be used on a map key or value.

I know the docs can use some work, I have some thoughts about what I wanted to do in #100 and I do intend to do a "Typing the untyped" sorta page.

**Comment by ctison** [comment]
Thanks, it looks like https://serde.rs/remote-derive.html.
I will stick with:
```rs
#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
pub struct Person<I = surrealdb::sql::Thing> {
  id: I,
}
```

**Comment by okhsunrog** [comment]
@oscartbeaumont this doesn't work for me for some reason:
```rust
#[serde_as]
#[derive(Error, Debug, Serialize, specta::Type)]
pub enum LplError {
    #[error("IO error: {0}")]
    #[specta(type = String)]
    Io(#[from] #[serde_as(as = "DisplayFromStr")] io::Error),
    #[error("Frame too large: {size} bytes (max: {max} bytes)")]
    FrameTooLarge { size: usize, max: usize },
    #[error("CRC mismatch: expected {expected:04x}, got {received:04x}")]
    InvalidCrc { expected: u16, received: u16 },
    #[error("Frame too small: {size} bytes (min: {min} bytes)")]
    FrameTooSmall { size: usize, min: usize },
    #[error("Invalid frame: {0}")]
    InvalidFrame(String),
}
```

I get compilation error:
```
error: specta: Found unsupported enum attribute 'type'
  --> fwupd-lib/src/error.rs:14:14
   |
14 |     #[specta(type = String)]
   |              ^^^^

```

**Comment by oscartbeaumont** [comment]
Are you using version 1 or 2 or Specta. This will require using a prerelease of version 2.

**Comment by okhsunrog** [comment]
@oscartbeaumont that's what I have in Cargo.toml:
```
specta = { version = "=2.0.0-rc.22", features = ["uuid", "chrono", "serde", "derive"], optional = true }
```
Maybe I need a different version or some feature enabled?
