### ISSUE TITLE
Deriving `Type` in `macro_rules!`

### ISSUE THREAD

**Issue by RedPhoenixQ** [oscartbeaumont/specta#211]
I'm trying to create structs inside a `macro_rules!` but i get the following error
```sh
error: specta: Cannot get path from type `i32`
   --> bevy_backend\src\rpc.rs:298:29
    |
298 |                 struct Test($incomming_type);
    |                             ^^^^^^^^^^^^^^^
...
302 |         testing!(i32);
```
with this example code:
```rust
fn example() {
    macro_rules! testing {
        ($incomming_type:ty) => {
            #[derive(serde::Serialize, specta::Type)]
            #[specta(inline, crate = "specta")]
            struct Test($incomming_type);
        };
    }
    testing!(i32);
}
```

I found the `#[specta(inline, crate = "...")]` from the `rspc::selection!` macro, but i can't make that work either.

It is probably some macro ordering issue but I'm not familiar enough with macros to figure out how to fix it.

**Comment by oscartbeaumont** [comment]
Calling `specta::Type` is fine within a macro as long as the tokens all exists. In your case the fields are dynamic and are not "resolved" prior to the Specta macro being invoked.

Specta needs to be able to "see" the fields to properly introspect them.

For this to work you would have to change the order that the proc macro's are invoked which I don't think is possible.

You could possibly look at doing a manual `specta::Type` implementation but it can be pretty error-prone.

Can you explain more about your usecase, in-case there is another workaround that could be viable? Is it specifically with single-field tuple structs?
