### ISSUE TITLE
result value and error transpiled to inline

### ISSUE THREAD

**Issue by Natejoestev** [oscartbeaumont/specta#212]
I noticed any type passed into a `Result<>` as value or error does not form into a separate type in the typescript definitions.

example code:
```rs
#[derive(serde::Serialize, specta::Type)]
enum MyValue {
  myThing {name: String}
}

#[tauri::command]
#[specta::specta]
fn my_func() -> Result<MyValue, boolean> {
  Ok(MyValue:myThing {
    name: "test".to_string()
  })
}
```

what it transpiles to:
```ts
export const commands = {
  async myFunc() : Promise<__Result__<{name:String}, boolean>> { .... }
}
```

notice how the result does not reference to a custom type.
how i would expect it to output:
```ts
export const commands = {
  async myFunc() : Promise<__Result__<MyValue, boolean>> { .... }
}

export type MyValue = { name: string };
```

thanks to `icb` in the tauri discord server for helping me discover this error.
I got lead to this because my type that i pass to the result i need to use other places in the frontend.

PS. the indenting is wacked up

**Comment by oscartbeaumont** [comment]
Which version of Tauri Specta/Specta are you using?

**Comment by oscartbeaumont** [comment]
Actually, I have a feeling this issue will be fixed by https://github.com/oscartbeaumont/specta/commit/d3c747650b4eef5878537640759bac93d2dc46af which is unreleased.
