### ISSUE TITLE
Applying serde transparency

### ISSUE THREAD

**Issue by amosjyng** [oscartbeaumont/specta#234]
I have a wrapper class around UUID that I tell serde to ignore via the `transparent` attribute:

```rs
#[derive(
    AsExpression,
    FromSqlRow,
    Debug,
    Clone,
    PartialEq,
    Eq,
    Hash,
    specta::Type,
    Serialize,
    Deserialize,
)]
#[diesel(sql_type = Text)]
#[serde(transparent)]
pub struct EntityId {
    pub uuid: Uuid,
}
```

Unfortunately Specta generates the type

```ts
export type EntityId = { uuid: string }
```

So for example, if I have

```rs
#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
pub struct LlmCall {
    pub id: EntityId,
    ...
}
```

then serde serializes it as

```json
{
    "id": "c13c1e67-2de3-48de-a34c-a32079c03316",
    ...
}
```

whereas Specta expects

```ts
export type LlmCall = { id: EntityId; ... }
```

and so I am unable to assign `llm_call.id` to a string without TypeScript complaining.

I see from some other issues that `#[specta(transparent)]` is an attribute I can use, but I don't see any documentation on what it means, and in any case applying it here doesn't seem to make a difference in Specta's output. Please let me know if there's a way to solve this problem :)

Thanks!

**Comment by oscartbeaumont** [comment]
Are you using Specta v1 or v2?

This looks to be fixed on Specta v2 and bug fixes are not currently being backported.

**Comment by amosjyng** [comment]
Ah I'm using v1. If I only upgrade Specta to v2, I get the error

```
error[E0277]: the trait bound `tauri::State<'_, ZammDatabase>: Type` is not satisfied
   --> src/commands/llms/get_api_calls.rs:30:1
    |
30  |   #[specta]
    |   ^^^^^^^^^ the trait `Type` is not implemented for `tauri::State<'_, ZammDatabase>`
```

for my function

```rs
#[tauri::command(async)]
#[specta]
pub async fn get_api_calls(
    database: State<'_, ZammDatabase>,
    offset: i32,
) -> ZammResult<Vec<LightweightLlmCall>> {
    get_api_calls_helper(&database, offset).await
}
```

which previously did not present a problem on Specta v1.

If I try also upgrading tauri-specta to `2.0.0-rc.10`, I get a dependency resolution conflict because I'm still on Tauri v1.

**Comment by oscartbeaumont** [comment]
Specta v2 does not support Tauri v1 and vice versa for the exact same reason you end up with the dependency resolution conflicts.
