### ISSUE TITLE
Doc is ambiguous error when using specta with certain crates

### ISSUE THREAD

**Issue by Isaac-Leonard** [oscartbeaumont/specta#235]
I'm attempting to use specta to generate the typescript types for an automatically derived enum that I'm generating with the strum crate.
I've pasted my code below:
```
#[enum_dispatch(Tool)]
#[derive(EnumDiscriminants)]
#[strum_discriminants(derive(Serialize, Deserialize, Type))]
pub enum ToolData {
    TraceGeometries(TraceGeometries),
}
```
When attempting to compile this I get the following error:
```
      error[E0659]: `doc` is ambiguous
  --> src/tools.rs:49:10
   |
49 | #[derive(EnumDiscriminants)]
   |          ^^^^^^^^^^^^^^^^^ ambiguous name
   |
   = note: ambiguous because of a name conflict with a builtin attribute
   = note: `doc` could refer to a built-in attribute
note: `doc` could also refer to the derive helper attribute defined here
  --> src/tools.rs:50:54
   |
50 | ...serialize, Type))]
   |               ^^^^
   = note: this error originates in the derive macro `EnumDiscriminants` (in Nightly builds, run with -Z macro-backtrace for more info)

```
While the error originates from the EnumDiscriminants macro, as it inserts a doc comment at the top of the derived enum, the error seems to be caused by specta aliasing or doing something odd with the `doc` macro.
I'm also not the only one to have experienced this issue it seems either as seen here: https://users.rust-lang.org/t/ambiguous-attribute-caused-by-proc-macro-derive/111088/2
Would this be easy to fix? If so I'm happy to make a pull request

**Comment by Isaac-Leonard** [comment]
Note I'm using specta v1.0.5 with tauri-specta v1.0.2, happy to upgrade to v2 if this issue is already fixed and tauri-specta will work the same

**Comment by oscartbeaumont** [comment]
Specta registers itself to listen to Rust's built-in doc comments. I've definitely seen this error before in relation to Specta but I don't recall the context. If you said it's fixed in v2 then yeah it probs is.

To use Specta v2 you must have Tauri Specta v2 which also requires Tauri v2. It's a big rough at the moment, sorry, but it's hard for us to avoid it!

**Comment by Isaac-Leonard** [comment]
Okay, I've got it working now with v2, thank you
Not related but do you know if you plan to add any helper functions to the Result type outputs?
Previously it would just throw an error which is probably not good for production but is useful for rapid iterations.
There's a lot of existing ts result types that people have written to simulate rust like error handling, maybe it might be worth integrating with one of them.

**Comment by oscartbeaumont** [comment]
Great you got it working!

#119
