### ISSUE TITLE
`Type` is not implemented for serde_json `Map` & `Value`

### ISSUE THREAD

**Issue by kareemmahlees** [oscartbeaumont/specta#236]
## Context
I was just upgrading my Tauri app stack to V2 and I sat all the versions to be identical to what mentioned [here](https://github.com/oscartbeaumont/tauri-specta/blob/main/docs/v2.md#installation).
The only problem I am facing is that the `Type` trait is not implemented for `Map` and `Value` types of serde_json.

I tried enabling the `serde` feature, which should be enabled by default, but with no use.
## Environment info  
- Tauri version: `2.0.0-beta.19`
- specta version: `2.0.0-rc.12`
- tauri-specta version: `2.0.0-rc.5`

**Comment by oscartbeaumont** [comment]
You will need to enable the `serde_json` feature.

I've split it from the Serde feature as Serde supports other languages such as yaml, toml, etc.

**Comment by oscartbeaumont** [comment]
The `serde` feature is probaly still required alongside the `serde_json` feature.

The `serde` feature is responsible for checking your structs are valid in terms of Serde's runtime requirements in the Typescript exporter.
