### ISSUE TITLE
Support custom serde serialization implementations (`http-serde`)?

### ISSUE THREAD

**Issue by sleeyax** [oscartbeaumont/specta#280]
Is it possible to use this crate with the [http-serde](https://crates.io/crates/http-serde) crate for example?

My struct looks like this:

```rs
#[derive(Clone, Debug, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub(crate) struct SerializableHttpResponse {
  pub(crate) status: String,
  pub(crate) version: String,
  #[serde(with = "http_serde::header_map")]
  pub(crate) headers: hyper::HeaderMap,
  pub(crate) body: Vec<u8>,
}
```

But it seems like the `#[serde(with = "http_serde::header_map")]`  attribute is being ignored by specta:

```rs
error[E0277]: the trait bound `HeaderMap: specta::Type` is not satisfied
  --> src/serializable/http_response.rs:19:23
   |
19 |   pub(crate) headers: hyper::HeaderMap,
   |                       ^^^^^^^^^^^^^^^^ the trait `specta::Type` is not implemented for `HeaderMap`
   |
   = help: the following other types implement trait `specta::Type`:
             &'a T
             &'a [T]
             &'a str
             ()
             (T10, T11, T12, T13)
             (T11, T12, T13)
             (T12, T13)
             (T13,)
           and 91 others
```

**Comment by oscartbeaumont** [comment]
Specta has no way to know what the function declared in `with` actually does so it currently just ignores it. In the future I am fairly sure we should be more strict and automatically change all fields that have a `with` to `any` and require the type to be explicit type set by the user.

For your specific problem, I think your best bet would probally be a remote implementation. Something like:

```rs
// This one is written to express the types.
#[derive(Type)]
// This will make it be `impl Type for SerializableHttpResponse` instead of `impl Type for SerializableHttpResponseTypes`
#[specta(remote = SerializableHttpResponse)]
pub struct SerializableHttpResponseTypes {
    pub status: String.
    // It's on you to ensure this matches `http_serde` cause idk what it serializes as.
    pub headers: HashMap<String, String>,
}

#[derive(Serialize, Deserialize, Type)]
pub struct SerializableHttpResponse {
   // ...
}
```

**Comment by sleeyax** [comment]
Thanks a lot for a reply! This library is still a bit magical to me so I really appreciate you taking the time to help me out. 

Your suggestion works (but the second `Type` on `SerializedHttpResponse` should be removed, it's a typo I suppose).

**Comment by sleeyax** [comment]
I believe this issue is also related to: #86.

**Comment by oscartbeaumont** [comment]
Whoops.

I am gonna close this then in favor of #86 tracking future work in this area. Feel free to comment again if you do run into any more issues with it!

**Comment by sleeyax** [comment]
Technically I'm not using the `serde_with` or `serde_as` crates, but given they are based on serde's `with` attribute option I suppose it points to the same issue, yes.
