### ISSUE TITLE
Field keys and string union types block on reserved words list

### ISSUE THREAD

**Issue by ajmcquilkin** [oscartbeaumont/specta#51]
I'm using `specta` in a context in which there are many potential collisions with the list of reserved TS words, as defined [here](https://github.com/oscartbeaumont/specta/blob/37b829156f27b7167cf057c03083c5b2222f33d9/src/lang/ts/mod.rs#L412). I'm filing this because, to the best of my knowledge, neither object keys nor string union types need to avoid these keywords. For context, I'm generating these types with the  `specta::export::ts_with_cfg` method.

![Screenshot_20230224_172427](https://user-images.githubusercontent.com/46639306/221305023-9e7010d5-ca60-4e85-94cb-8d5565f8d1ff.png)
*Needed to change key `"from"` to `"nodeFrom"` to get successful compilation due to reserved keyword `"from"`.*

![Screenshot_20230224_165845](https://user-images.githubusercontent.com/46639306/221301302-79658c74-94d7-4972-801c-863bfdf4f891.png)
*Needed to change string `"default"` to `"defaultMode"` to get successful compilation due to reserved keyword `"default"`.*

**Comment by oscartbeaumont** [comment]
Thanks for reporting. The second one is definitely a mistake in the checker. The first one I think was intended but it's probably worth us rethinking it because it's a very arbitrary restriction.

---

Personal notes:
 - Maybe use `ExportConfiguration` to allow configuring handling of reserved keywords?
 - For tauri-specta will need to prevent keywords in some object keys because we use them as function args
       -  Eg. `function demo2(from: "index.ts", for: "demo.ts", function: "todo");`
       - It's so odd `from` is fine but `for` and `function` is not in that example.

**Comment by ajmcquilkin** [comment]
Of course, also happy to provide more detailed examples if that's at all helpful.

**Comment by Brendonovich** [comment]
Might be worth consulting [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#keywords) for the specific list of reserved keywords - looks like `from` has 'special meaning in some contexts without being reserved words of any kind'.
