### ISSUE TITLE
[Bug]: [Option<Value>; 64] & Vec<Option<Value>> incorrect type conversion

### ISSUE THREAD

**Issue by Ziothh** [oscartbeaumont/specta#66]
Hi, I'm really enjoying the tooling you guys are building but i've come across a rather annoying issue whilst using rspc.

My types are not being converted correctly when using a struct with an array of size 64.
Is this a bug in the crate or something of my own doing (e.g. using the serde_big_array crate)?

Thanks in advance and keep up the great work!

Here's my code:

```rust
// ChessBoard.rs
use serde_big_array::BigArray;
use my_engine::core::pieces::ChessPiece;

#[derive(Debug, rspc::Type, serde::Serialize)]
pub struct ChessBoard(#[serde(with = "BigArray")] [Option<ChessPiece>; ChessBoard::SIZE]);

impl ChessBoard {
    pub const SIZE: usize = NUM_FILES * NUM_RANKS; // 64usize
    
    // Snip ---------
}
```

```typescript
// bindings.ts
/// What it generated
export type ChessBoard = ChessPiece | null[] // ChessPiece or null array

// What it should be generated as
export type ChessBoard = (ChessPiece | null)[] // Array of ChessPiece or null
```

**Comment by Ziothh** [comment]
UPDATE: I have tried using a Vec<Option<ChessPiece>> and still got the same result.

**Comment by Brendonovich** [comment]
Oh this is definitely a bug, it should work how you describe

**Comment by oscartbeaumont** [comment]
Good catch. Fixed in main will try and do a release soon wanna get a couple of other bug fixes in at the same time.

**Comment by Ziothh** [comment]
Great! 
I'm using the re-export in rspc. Any idea when rspc would use the updated version?

I'll use specta for now. Thanks for the quick fix!

**Comment by oscartbeaumont** [comment]
Am hoping to sometime this week.
