### ISSUE TITLE
Empty output not compatible with vite transforrm

### ISSUE THREAD

**Issue by prestomation** [oscartbeaumont/specta#88]
First, thanks for the awesome library! It only took me a few minutes to get it integrated into my tauri build and into my js app.

I'm using tauri with a remote domain. This means that the javascript that uses specta types is sent over the internet and not shipped with the tauri app. This means that extra care needs to be taken when updating these APIs specs as we now have a versioned interface.

Because of this, as a rule I ensure that all commands have an input and an output type, even if it's empty. This way I can use `invoke({})` and I can add new optional parameters to the type later without breaking anything.

This doesn't quite work with specta and my vite build, take a type like:
```
#[derive(Deserialize, Type)]
#[serde(rename_all = "camelCase")]
#[serde(default)]
pub(super) struct MyEmptyInput {
}
```

With the typescript output this will generate
```
export type MyEmptyInput<> = null
```

This looks to be valid typescript, but my vite transformer chokes on this as it fails with `  Expected identifier but found ">"`, pointing at the `<>`.

Now it's entirely possible that vite is broken and is where the improvement needs to go, but I wanted to report this in case there is something specta should be doing differently or if you have any other suggestions. Thanks!

**Comment by oscartbeaumont** [comment]
This does seem like a bug on our side.

The generic coming from nowhere makes no sense and the `null` instead of `{}` I can understand knowing the internals of Specta but doesn't seem logical from a user perspective. From quickly thinking about it `()` should be null and `struct A {}` should be `{}` as your expecting.

**Comment by oscartbeaumont** [comment]
The excess generics issue was an easy fix. Specta does need to step up its testing of definition types (`export type A = ...;`) as right now we only really test the inlined type (`...`) and inlined types have the generics already resolved. That being said my understanding is that `export type MyEmptyInput<> = null` should be valid Typescript so if your Vite transformer is failing it's probably a bug in it.

For the fact that the result is `null`, I double-checked Serde's behavior and got surprised by the results [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=171b77390a2b1d6d37939a55db194df7). I have updated Specta to follow as Specta has to match Serde's JSON's.

<details>
  <summary>Some stuff for my future reference</summary>
  
  ```rust
How it works:

`struct A()` - Tuple::Unnamed = `[]`
`struct A` or `()`   - Tuple::Named( fields.is_empty() ) = `null`

(given these are the same `Object::Unnamed` is redundant so doesnt make sense being added)
`struct A {}` - Object::Unnamed = `Record<string, never>`
`struct A {}` - Object::Named( fields.is_empty() ) (from: `struct A {}`) = `Record<string, never>`

(really `Enum::Unnamed` is also not needed)
Enum( fields.is_empty() ) = `never`

  ```
</details>
